-- Safetyreport Community Map
-- Initial Supabase schema draft.
-- Phone numbers remain in Supabase Auth. Application tables reference auth.users.id only.

create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

grant usage on schema private to service_role;

create table private.contributor_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    consent_version text not null,
    privacy_policy_version text not null,
    consented_at timestamptz not null default now(),
    revoked_at timestamptz,
    status text not null default 'active'
        check (status in ('active', 'suspended', 'deletion_pending')),
    last_upload_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table private.upload_snapshots (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references private.contributor_profiles(user_id) on delete cascade,
    schema_version integer not null check (schema_version > 0),
    source_mode text not null
        check (source_mode in ('mobile_standalone', 'mobile_server', 'safetyreport_server')),
    state text not null default 'staged'
        check (state in ('staged', 'quarantined', 'active', 'superseded', 'deleted')),
    client_generated_at timestamptz not null,
    data_through_at timestamptz,
    expected_point_count integer not null
        check (expected_point_count between 0 and 10000),
    received_point_count integer not null default 0
        check (received_point_count between 0 and 10000),
    payload_sha256 text not null
        check (payload_sha256 ~ '^[0-9a-f]{64}$'),
    received_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '1 hour'),
    finalized_at timestamptz,
    superseded_at timestamptz,
    superseded_by uuid references private.upload_snapshots(id) on delete set null,
    quarantine_reason text,
    location_key_version integer not null default 1
);

-- Partial dedupe: a payload hash blocks re-use only while it is still live.
-- A full-column unique constraint would reject a legitimate A -> B -> A
-- re-upload because of the old superseded row.
create unique index upload_snapshots_payload_dedupe
    on private.upload_snapshots(user_id, payload_sha256)
    where state in ('staged', 'active', 'quarantined');

create unique index upload_snapshots_one_active_per_user
    on private.upload_snapshots(user_id)
    where state = 'active';

create index upload_snapshots_state_received_idx
    on private.upload_snapshots(state, received_at);

create table private.upload_points (
    id bigint generated by default as identity primary key,
    snapshot_id uuid not null references private.upload_snapshots(id) on delete cascade,
    period_year smallint not null check (period_year between 2020 and 2200),
    category text not null check (category in ('traffic', 'parking', 'other')),
    location_key text not null check (location_key ~ '^[0-9a-f]{64}$'),
    lat double precision not null check (lat between 32.0 and 39.5),
    lng double precision not null check (lng between 124.0 and 132.0),
    address text not null check (char_length(address) between 1 and 200),
    region text not null default '' check (char_length(region) <= 100),
    total_count integer not null check (total_count >= 0),
    accepted_count integer not null default 0 check (accepted_count >= 0),
    processing_count integer not null default 0 check (processing_count >= 0),
    rejected_count integer not null default 0 check (rejected_count >= 0),
    withdrawn_count integer not null default 0 check (withdrawn_count >= 0),
    fine_count integer not null default 0 check (fine_count >= 0),
    status_counts jsonb not null default '{}'::jsonb
        check (jsonb_typeof(status_counts) = 'object'),
    disposition_counts jsonb not null default '{}'::jsonb
        check (jsonb_typeof(disposition_counts) = 'object'),
    agency_counts jsonb not null default '{}'::jsonb
        check (jsonb_typeof(agency_counts) = 'object'),
    manager_counts jsonb not null default '{}'::jsonb
        check (jsonb_typeof(manager_counts) = 'object'),
    created_at timestamptz not null default now(),
    check (accepted_count <= total_count),
    check (processing_count <= total_count),
    check (rejected_count <= total_count),
    check (withdrawn_count <= total_count),
    check (fine_count <= total_count),
    check (accepted_count + processing_count + rejected_count + withdrawn_count <= total_count),
    unique (snapshot_id, period_year, category, location_key)
);

create index upload_points_snapshot_idx
    on private.upload_points(snapshot_id);

create index upload_points_location_idx
    on private.upload_points(period_year, category, location_key);

create table private.upload_chunks (
    snapshot_id uuid not null references private.upload_snapshots(id) on delete cascade,
    chunk_index integer not null check (chunk_index >= 0),
    point_count integer not null check (point_count between 0 and 500),
    chunk_sha256 text not null check (chunk_sha256 ~ '^[0-9a-f]{64}$'),
    received_at timestamptz not null default now(),
    primary key (snapshot_id, chunk_index)
);

create table private.abuse_events (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    request_id text not null,
    event_type text not null,
    severity text not null check (severity in ('info', 'warning', 'critical')),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index abuse_events_created_idx
    on private.abuse_events(created_at);

-- Edge Functions are stateless; rate-limit counters live here.
-- Buckets that key on an IP store a hash, never the raw address.
create table private.rate_limits (
    bucket text not null,
    window_start timestamptz not null,
    request_count integer not null default 0 check (request_count >= 0),
    primary key (bucket, window_start)
);

create index rate_limits_window_idx
    on private.rate_limits(window_start);

alter table private.contributor_profiles enable row level security;
alter table private.upload_snapshots enable row level security;
alter table private.upload_points enable row level security;
alter table private.upload_chunks enable row level security;
alter table private.abuse_events enable row level security;
alter table private.rate_limits enable row level security;

-- Publicly safe materialized output. It is still read only through the Edge Function.
-- period_year 0 and category 'all' hold pre-aggregated "all" combinations;
-- contributor_count cannot be derived by summing per-year/per-category rows.
create table public.public_map_points (
    period_year smallint not null check (period_year = 0 or period_year between 2020 and 2200),
    category text not null check (category in ('all', 'traffic', 'parking', 'other')),
    location_key text not null check (location_key ~ '^[0-9a-f]{64}$'),
    lat double precision not null check (lat between 32.0 and 39.5),
    lng double precision not null check (lng between 124.0 and 132.0),
    address text not null check (char_length(address) between 1 and 200),
    region text not null default '' check (char_length(region) <= 100),
    total_count bigint not null check (total_count >= 0),
    accepted_count bigint not null default 0 check (accepted_count >= 0),
    processing_count bigint not null default 0 check (processing_count >= 0),
    rejected_count bigint not null default 0 check (rejected_count >= 0),
    withdrawn_count bigint not null default 0 check (withdrawn_count >= 0),
    fine_count bigint not null default 0 check (fine_count >= 0),
    contributor_count integer not null check (contributor_count > 0),
    confidence text not null check (confidence in ('low', 'medium', 'high')),
    status_breakdown jsonb not null default '[]'::jsonb
        check (jsonb_typeof(status_breakdown) = 'array'),
    disposition_breakdown jsonb not null default '[]'::jsonb
        check (jsonb_typeof(disposition_breakdown) = 'array'),
    agency_breakdown jsonb not null default '[]'::jsonb
        check (jsonb_typeof(agency_breakdown) = 'array'),
    category_breakdown jsonb not null default '[]'::jsonb
        check (jsonb_typeof(category_breakdown) = 'array'),
    updated_at timestamptz not null default now(),
    primary key (period_year, category, location_key)
);

create index public_map_points_bbox_idx
    on public.public_map_points(period_year, category, lat, lng);

alter table public.public_map_points enable row level security;

-- No anon/authenticated policies are intentionally created.
-- Only the service role used by the public-map Edge Function can read this table.
revoke all on table public.public_map_points from anon;
revoke all on table public.public_map_points from authenticated;
grant select, insert, update, delete on table public.public_map_points to service_role;

revoke all on all tables in schema private from public;
revoke all on all tables in schema private from anon;
revoke all on all tables in schema private from authenticated;
grant select, insert, update, delete on all tables in schema private to service_role;
grant usage, select on all sequences in schema private to service_role;

alter default privileges in schema private revoke all on tables from public;
alter default privileges in schema private revoke all on tables from anon;
alter default privileges in schema private revoke all on tables from authenticated;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger contributor_profiles_touch_updated_at
before update on private.contributor_profiles
for each row execute function private.touch_updated_at();

create or replace function public.internal_activate_snapshot(
    p_snapshot_id uuid,
    p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_expected integer;
    v_received integer;
    v_payload_sha256 text;
    v_computed_sha256 text;
begin
    -- Serializes activation for one contributor.
    perform 1
      from private.contributor_profiles
     where user_id = p_user_id
       and status = 'active'
       and revoked_at is null
     for update;

    if not found then
        raise exception 'active contributor profile not found';
    end if;

    select expected_point_count, received_point_count, payload_sha256
      into v_expected, v_received, v_payload_sha256
      from private.upload_snapshots
     where id = p_snapshot_id
       and user_id = p_user_id
       and state = 'staged'
     for update;

    if not found then
        raise exception 'staged snapshot not found';
    end if;

    if v_expected <> v_received then
        raise exception 'snapshot point count mismatch';
    end if;

    -- payload_sha256 = sha256 of all chunk hashes concatenated in chunk order
    -- (docs/data-contract.md section 7).
    select encode(extensions.digest(
               coalesce(string_agg(chunk_sha256, '' order by chunk_index), ''),
               'sha256'), 'hex')
      into v_computed_sha256
      from private.upload_chunks
     where snapshot_id = p_snapshot_id;

    if v_computed_sha256 is distinct from v_payload_sha256 then
        raise exception 'snapshot payload hash mismatch';
    end if;

    update private.upload_snapshots
       set state = 'superseded',
           superseded_at = now(),
           superseded_by = p_snapshot_id
     where user_id = p_user_id
       and state = 'active';

    update private.upload_snapshots
       set state = 'active',
           finalized_at = now()
     where id = p_snapshot_id;

    update private.contributor_profiles
       set last_upload_at = now()
     where user_id = p_user_id;
end;
$$;

revoke all on function private.touch_updated_at() from public;
revoke all on function public.internal_activate_snapshot(uuid, uuid) from public;
revoke all on function public.internal_activate_snapshot(uuid, uuid) from anon;
revoke all on function public.internal_activate_snapshot(uuid, uuid) from authenticated;
grant execute on function public.internal_activate_snapshot(uuid, uuid) to service_role;

-- Retention enforcement (docs/database.md section 9). Deleting a snapshot
-- cascades to its points and chunks.
create or replace function public.internal_cleanup_expired()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    delete from private.upload_snapshots
     where state = 'staged'
       and expires_at < now();

    delete from private.upload_snapshots
     where state = 'superseded'
       and superseded_at < now() - interval '30 days';

    delete from private.upload_snapshots
     where state = 'quarantined'
       and received_at < now() - interval '7 days';

    delete from private.abuse_events
     where created_at < now() - interval '90 days';

    delete from private.rate_limits
     where window_start < now() - interval '2 days';
end;
$$;

revoke all on function public.internal_cleanup_expired() from public;
revoke all on function public.internal_cleanup_expired() from anon;
revoke all on function public.internal_cleanup_expired() from authenticated;
grant execute on function public.internal_cleanup_expired() to service_role;

-- Schedule hourly once pg_cron is enabled:
-- select cron.schedule('community-map-cleanup', '17 * * * *',
--     'select public.internal_cleanup_expired()');

comment on table private.contributor_profiles is
    'Participation and consent metadata. Phone numbers remain exclusively in auth.users.';

comment on table private.upload_points is
    'Per-contributor aggregate map points. Manager names stay private-only. Never store report IDs, vehicle numbers, report text, attachments, or exact event timestamps.';

comment on table public.public_map_points is
    'De-identified, location-level aggregates exposed only through the public-map Edge Function.';
